fix release pipeline; Drop setup-nuget action; use ubuntu instead of windows; don't release as pre-release although we use System.Text v9 (#12)
* fix release pipeline

* ignore NU1504

maybe fixes
>  Error: C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5104: Warning As Error: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Text.Json [9.0.0-rc.2.24473.5, )" or update the version field in the nuspec. [D:\a\malo-ident-net-models\malo-ident-net-models\MaLoIdentModels\MaLoIdentModels\MaLoIdentModels.csproj]

I want to release as real release, no pre-release.

* ignore NU1504 (#13)

maybe fixes
>  Error: C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5104: Warning As Error: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Text.Json [9.0.0-rc.2.24473.5, )" or update the version field in the nuspec. [D:\a\malo-ident-net-models\malo-ident-net-models\MaLoIdentModels\MaLoIdentModels\MaLoIdentModels.csproj]

I want to release as real release, no pre-release.

Co-authored-by: Konstantin <konstantin.klein+github@hochfrequenz.de>

* Update release_nuget.yml

* don't pin system.text.json

Error: C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5104: Warning As Error: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Text.Json [9.0.0-rc.2.24473.5, )" or update the version field in the nuspec. [D:\a\malo-ident-net-models\malo-ident-net-models\MaLoIdentModels\MaLoIdentModels\MaLoIdentModels.csproj]

* www

https://gitkraken.dev/link/drafts/23475fc5-edc2-4da5-9a67-54fd1fef15d1?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPTTNWcm1jNS1QMWpCIl0=

* xxx

Run dotnet nuget push ./bin/Release/*.nupkg --api-key $NUGET_ORG_PUSH_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
  dotnet nuget push ./bin/Release/*.nupkg --api-key $NUGET_ORG_PUSH_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    DOTNET_ROOT: C:\Program Files\dotnet
    GIT_TAG_NAME: 0.2.6
    NUGET_ORG_PUSH_TOKEN: ***
error: Source parameter was not specified.

* aaaaaaa

* switch back to ubuntu-latest

* prettier

---------

Co-authored-by: Konstantin <konstantin.klein+github@hochfrequenz.de>